
#ifndef M68060PAIRABILITYTESTS_H
#define M68060PAIRABILITYTESTS_H

#include "M68060UOp.h"

typedef enum
{
	PairabilityTestResult_Success,
	PairabilityTestResult_Test2Failure_FirstInstructionIs_pOEPOnly,
	PairabilityTestResult_Test2Failure_SecondInstructionIsNot_pOEPOrsOEP,
	PairabilityTestResult_Test3Failure_SecondInstructionUsesPCRelativeAddressing,
	PairabilityTestResult_Test4Failure_BothInstructionsReferenceMemory,
	PairabilityTestResult_Test5Failure_SecondInstructionBaseRegisterDependsOnFirstInstructionAguResult,
	PairabilityTestResult_Test5Failure_SecondInstructionBaseRegisterDependsOnFirstInstructionIeeResult,
	PairabilityTestResult_Test5Failure_SecondInstructionIndexRegisterDependsOnFirstInstructionAguResult,
	PairabilityTestResult_Test5Failure_SecondInstructionIndexRegisterDependsOnFirstInstructionIeeResult,
	PairabilityTestResult_Test6Failure_SecondInstructionIeeARegisterDependsOnFirstInstructionAguResult,
	PairabilityTestResult_Test6Failure_SecondInstructionIeeARegisterDependsOnFirstInstructionIeeResult,
	PairabilityTestResult_Test6Failure_SecondInstructionIeeBRegisterDependsOnFirstInstructionAguResult,
	PairabilityTestResult_Test6Failure_SecondInstructionIeeBRegisterDependsOnFirstInstructionIeeResult,
} PairabilityTestResult;

const char* PairabilityTestResultToString(PairabilityTestResult pairabilityTestResult);

PairabilityTestResult checkPairability(UOp* UOp0, UOp* UOp1);

#endif
